// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThursdayMarket.DataAccess.Data;

#nullable disable

namespace ThursdayMarket.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230715155015_moreSeedingDataForProduct")]
    partial class moreSeedingDataForProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThursdayMarket.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Fruits"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Vegetables"
                        });
                });

            modelBuilder.Entity("ThursdayMarket.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ISBN = "100",
                            ImageUrl = "",
                            Name = "Banana",
                            Price = 3.0,
                            Quantity = 1.0,
                            Supplier = "Mall city",
                            Weight = 3.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            ISBN = "100",
                            ImageUrl = "",
                            Name = "Apple",
                            Price = 4.0,
                            Quantity = 1.0,
                            Supplier = "Mall city",
                            Weight = 3.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            ISBN = "101",
                            ImageUrl = "",
                            Name = "Orange",
                            Price = 2.5,
                            Quantity = 1.0,
                            Supplier = "Fruit King",
                            Weight = 2.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            ISBN = "102",
                            ImageUrl = "",
                            Name = "Carrot",
                            Price = 1.5,
                            Quantity = 1.0,
                            Supplier = "Veggie Farm",
                            Weight = 1.0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            ISBN = "103",
                            ImageUrl = "",
                            Name = "Grapes",
                            Price = 5.0,
                            Quantity = 1.0,
                            Supplier = "Vineyard Co.",
                            Weight = 4.0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            ISBN = "104",
                            ImageUrl = "",
                            Name = "Broccoli",
                            Price = 2.0,
                            Quantity = 1.0,
                            Supplier = "Veggie Farm",
                            Weight = 2.0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            ISBN = "105",
                            ImageUrl = "",
                            Name = "Watermelon",
                            Price = 6.0,
                            Quantity = 1.0,
                            Supplier = "Fruit King",
                            Weight = 7.0
                        });
                });

            modelBuilder.Entity("ThursdayMarket.Models.Product", b =>
                {
                    b.HasOne("ThursdayMarket.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ThursdayMarket.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
